import string

GENE_ITEMS_POOL = tuple(_s for _s in string.ascii_lowercase)
GENE_SIZE_LIMITS = 2, 2

INDIVIDUAL_MUTATION_PROBABILITY_LIMITS = 0, 0.1
INDIVIDUAL_RESOURCE_CONSUMPTION_RATE_LIMITS = 0.5, 1.5

GENOME_SIZE_LIMITS = 5, 10

CONSTRAINT_GENES_NUMBER_LIMITS = 1, 1
CONSTRAINT_REWARD_LIMITS = 0, 1

DEFAULT_COSMOS_RESOURCES = 200
DEFAULT_COSMOS_RESOURCE_REGENERATION_RATE = 10

DEFAULT_POPULATION_SIZE = 50
DEFAULT_ENVIRONMENT_SIZE = 60
