import string

GENE_ITEMS_POOL = tuple(_s for _s in string.ascii_lowercase)
GENE_SIZE_LIMITS = 1, 3

INDIVIDUAL_MUTATION_PROBABILITY_LIMITS = 0, 0.01
INDIVIDUAL_RESOURCE_CONSUMPTION_RATE_LIMITS = 0, 1

GENOME_SIZE_LIMITS = 1, 5

CONSTRAINT_GENES_NUMBER_LIMITS = 1, 2
CONSTRAINT_REWARD_LIMITS = 0, 1

DEFAULT_COSMOS_RESOURCES = 3

DEFAULT_POPULATION_SIZE = 10
DEFAULT_ENVIRONMENT_SIZE = 30
